#+SETUPFILE: ~/hi/almennt/latex-hbv501.org
#+LATEX_HEADER: \lhead{Hugbúnaðarverkefni 1}\rhead{HBV501G 2020}
#+LANGUAGE: en

\begin{titlepage}

\newcommand{\HRule}{\rule{\linewidth}{0.5mm}} 

\center 

\textsc{\LARGE Háskóli Íslands}\\[1.5cm] 
\textsc{\Large Hugbúnaðarverkefni 1 (HBV501G)}\\[0.5cm] 
\textsc{\large Team 20}\\[0.5cm] % Hópanúmer
\HRule \\[0.4cm]
{ \huge \bfseries Verkefni 1}\\[0.4cm] % Heiti skjals
\HRule \\[1.5cm]
 
\begin{minipage}{0.8\textwidth}
\begin{flushleft} \large
\emph{Höfundar:}\\ %Nöfn á höfundum skýrslu.
Fannar Sævarsson (fas19@hi.is), kt.220591-3369\\
Harpa Dögg Hafsteinsdóttir (hdh20@hi.is), kt.040390-2519\\
Hrafnkell Sigurðarson (hrs70@hi.is), kt.261292-2979\\
Skúli Þór Bjarnason (sthb13@hi.is), kt.060473-5019\\
\smallskip
\emph{Kynning:}\\
Skúli Þór Bjarnason\\
\smallskip
\emph{Kennari:}\\
Andri Valur Guðjohnsen
\end{flushleft}
\end{minipage}

\vfill 

\includegraphics{pallas.jpg}\\[1cm]

\end{titlepage}
* Vision and Scope
** Vision statement
**** *For* senior citizens
**** *who* want to understand and control their tablet device, either Android or iOS
**** *the* tæknilæsi fyrir fullorðna
**** *is* an education platform focused on videos
**** *that* will allow the students to repeat and train their knowledge that they learned in the class and also be accessible to those who could not attend the class in person.
**** *the* students will be able to keep track of their progress, search and filter the content
****** the content is organized in classes/topics and consists of an introduction and a varying number of lecture videos, accompanied with text and images for further explanation
****** each class will have a quiz where students can test their understanding
**** *unlike*
****** websites and guides aiming at this demographic, our product is using videos in icelandic to demonstrate all the common use cases of tablet devices
****** voluntary helpers (mostly school kids), our approach is systematic and covers basic up to advanced usage
****** youtube channels, there is interaction to train and repeat new information
**** *our product* aims at improving the technical literacy of its users and make them more independent in their daily life.
** Business opportunity
The platform we are developing is based on material that was conceived this summer while teaching senior citizens the basic use of tablet devices in the social centers of Reykjavík. Although the course has its roots prior to the pandemic it wasn't until the lock down when it became obvious to local authorities how important it was to raise the technical skills level of the senior population, as too many of them were not able to handle the practical challenges that followed the isolation.
Hopefully the lock down will remain a singular event, but the basic problems of this demographic persists. The larger part is getting left behind when it comes to ensuring an independent life as more and more services are becoming digital, and some even digital only, not to mention the generation gap in communications’ preference.
So even under normal circumstances the demand for these courses are huge, and we were in no way able to fulfill the requests. This is where the platform we are developing will relieve the shortage of available classes and give students, who were not able to attend due to capacity restrictions, the opportunity to take the classes on their own. But it is also intended to offer the other students the possibility to rewatch and train their skills as they seem fit.
We conducted surveys at the end of every course while teaching and asked the students if they were willing to pay for the course (it was offered free of charge). Most of them were, although the amounts would not cover the cost of the whole initiative, so the platform would be dependent on public funding  or some form of sponsorship.
We believe that the platform can improve the daily lives of senior citizens by empowering their independence from family and social services by improving their technical literacy. The demand is enormous and the feedback we have had so far was overwhelmingly good.
\pagebreak
** Scope of initial releases
- Extensive classes on basic usage for both Android and iOS
- Specialized classes on topics such as communication and entertainment geared towards senior citizens and their needs
- Students can (but are not required) register an account and save their progress
- Registration can also be done through a third party like google and facebook
- Students can test their knowledge and understanding by using a quiz that is part of every class
- Students (that are registered) can post comments on videos, ask for clarification, point to differences in their devices and answer other students' questions.
\pagebreak
* Use Case: Fully dressed format
** Use Case 1
*** Name
Login
*** Primary actor
Student
*** Preconditions
- URL must be known
- Internet connectivity
- Credentials must be known
*** Success guarantee
User is authorized
*** Main success scenario
1. Student enters username
2. Student enters password
3. System or third party validate input
4. Student continues to his/her lectures
*** Extensions / alternate scenarios
**** 1-3) User continues without login
1. User chooses not to authenticate with the service
2. User continues to the main page, with the ability to view lecture videos
3. User chooses a topic and views a video, but the system does not track progress.
4. No automatic filtering based on OS preference
**** 2) Forgotten password
1. User clicks on ‘forgotten password’
2. User enters email/username/other authenticator
3. User is prompted to check email
4. User receives email with password reset instruction
5. User clicks a link in the email and is taken to a password reset page
*** Miscellaneous / open issues
Consider "rafræn skilríki"as an alternative
\pagebreak
** Use Case 2
*** Name
Create profile
*** Primary actor
Student
*** Preconditions
• URL must be known
• Internet connectivity
*** Success guarantee
Profile created
*** Main success scenario
1. Student chooses between login options
2. Student chooses operating system (iOS or Android)
3. Student chooses experience level
4. Student picks topics of interest
5. System creates and stores profile
*** Extensions / alternate scenarios
1a) Email exists
1. User is notified that the email they are trying to use is already in use in the system
2. Email field is highlighted and user prompted to enter another email address
1b) User already exists
1. User is notified that the current user already exists.
2. User is given the option to login as that user or to be taken to a ’forgot password’ page
1-4) Mandatory information not entered
1. User is notified that mandatory information is missing or malformed
2. Fields for the information required are highlighted
5a) User continues without creating profile
1. User chooses not to create a profile
2. User is still able to view lecture videos, but progress is not saved
\pagebreak
** Use Case 3
*** Name
Take a lesson
*** Primary actor
Student
*** Preconditions
Having a registered account
*** Success guarantee
Progress track was updated
*** Main success scenario
1. Student chooses a class
2. Student watches the lectures in chronological order
3. Student reads the accompanying text
4. Student takes the final quiz
*** Extensions / alternate scenarios
1a) Student didn’t finish the class last time
1. User is given the option to continue from where they were last
1b) Continues where he left off
1. User has chosen to continue from last time
2. User is automatically taken to the last page they were at, with previously unsubmitted answers stored in the system
*** Miscellaneous / open issues
Explore possibility to store state with browser
\pagebreak
* Use Case: brief format

- A student has arrived at the homepage. The student wants to see lessons on a specific topic. The student chooses keywords from a set of predefined keywords. The system processes the keywords and displays lessons related to the keywords that the student entered. The student finds the lesson they were looking for.

- A student has logged into their account and has finished a lesson on a certain topic. The student has a question related to the lesson they would like to ask. The student scrolls down to the bottom of the lecture and writes their question in a comment box and presses a button to post. The system posts the student’s question to the site under the lesson. Another student or a teacher can then post a reply to the first student’s question in the same way.

- A student has watched a video lesson and wants to test the things they learned. The student scrolls down and sees questions related to the material of the video. The student selects the answer to the questions that they believe to be correct and press a button to finish the quiz. The system compares the submitted answers to the correct answers and notifies the student about which ones they answered correctly. If the student thinks they can do better, they can press a button to retake the quiz.

- A student navigates to the website. The student has trouble reading the text on the website. The student presses a button at the top to increase the text size. The system responds by making the text larger. The student still finds the text too small and presses the button again. The system makes the text even larger. The student continues on with their studies.
